### PR TITLE
Add --default-load-balancer-scheme command line flag

### LINKED ISSUE #3820: Option to create public-facing LBs by default
I am migrating in-tree LB controller to AWS Loadbalancer controller, and this controller requires annotation to create public-facing NLB otherwise internal is not consistent in behavior with the old Classic Loadbalancers.

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue

Close #3820 

### Description

- Add --default-load-balancer-scheme command line flag
- For users want to use internet-facing by default
- References: #2840 

### Checklist
- [x] Added tests that cover your change (if possible)
image

- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
#### Controller abort if input invalid scheme
462545503_1347007176274827_493019330782235324_n

#### Controller log
462549570_1615707695958017_8990472531953553826_n

- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by phuhung273** [comment]
@shraddhabang may i know your thought on this PR

**Review by shraddhabang — APPROVED** [review]
/lgtm
/approve

**Comment by shraddhabang** [comment]
@phuhung273 The changes looks good to me. However, we need to review this with our security engineer internally. I will work on that. Will provide you updates when we get that review. Thanks for your contribution.

**Comment by phuhung273** [comment]
Thank @shraddhabang, im ready for that as discussed in the issue

**Review by zac-nixon — APPROVED** [review]

**Pull request merged**
