### PR TITLE
update prow script and e2e test

### PR DESCRIPTION
**Pull request by oliviassss**
### Description

1. Updated prow script for internal CI jobs running in isolated regions
2. added the cleanup step in multi_path_backend_test in AfterEach()
3. Add test coverage for internal ALB/NLB

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
all the ingress and service tests cases passed, no error in the controller logs. but the job failed in the end with the error message
```
Error: deadline surpassed waiting for AWS load balancers to be deleted: k8s-e2egroupafac4b78-3b654f1c2d
+ echo 'unable to delete cluster lb-controller-e2e-3456-1724866415791443968'
unable to delete cluster lb-controller-e2e-3456-1724866415791443968
+ return 1
+ echo 'unable to delete cluster lb-controller-e2e-3456-1724866415791443968'
unable to delete cluster lb-controller-e2e-3456-1724866415791443968
+ return 1
make: *** [Makefile:197: e2e-test] Error 1 
```
Need to reach out to the test account owners to take a further look from here.

**Comment by oliviassss** [comment]
Issue opened in `kubernetes/k8s.io`: https://github.com/kubernetes/k8s.io/issues/6086

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Pull request closed without merging**
