### PR TITLE
upgrade dependencies including controller-runtime & k8s 

### PR DESCRIPTION
**Pull request by M00nF1sh**
### Description
Upgrade the dependencies used:
* controller-runtime: v0.6.3 -> v0.9.2
* k8s: v0.18.6 -> v0.21.2
* github.com/aws/aws-sdk-go:  v1.15.18 -> v1.38.67

This PR is separated into 10 commits:
* update dependencies version including controller-runtime & k8s & aws-sdk-go: upgrade go mod & go sum
* update to use `admission/v1 `update internal code to use `admission/v1`: updated internal package to use admission/v1
* update to use IngressClassParametersReference: updated ingressClassParams reference's internal type per k8s changes
* update to use client.Object: updated to use client.Object per controller-runtime changes
* update to use context from controller-runtime: updated to use context instead of stopChan per controller-runtime changes
* update to use client.Object for eventHandlers: updated to use client.Object in eventHandlers per controller-runtime changes
* update ec2 mocks: re-generated EC2 mocks
* minor style & test case fixes: some minor test case and lint fixes
* force to use ConfigMapsResourceLock: force to use configmap leader-election instead of configmaplease leader-election
* update to use golang v1.16.3: updated to use golang v1.16.3

### Checklist
- [x] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by kishorj — APPROVED** [review]

**Comment by fawadkhaliq** [comment]
> update to use admission/v1 update internal code to use admission/v1: updated internal package to use admission/v1

Did you mean `admission/v1beta1 ` ?

Also, are there any backward compatibility concerns here?

**Comment by M00nF1sh** [comment]
> > update to use admission/v1 update internal code to use admission/v1: updated internal package to use admission/v1
> 
> Did you mean `admission/v1beta1 ` ?
> 
> Also, are there any backward compatibility concerns here?

admission/v1beta1 & admission/v1 are identical currently, both are supported in v1.16+. in next release, we'll update the manifest to use admission/v1 as well.
Also, for this change, it won't land in v2.2.1 but will be in v2.3.0. we decided to upgrade controller-runtime & k8s version dependencies in minor release only.

**Pull request merged**
