### PR TITLE
TargetGroupBinding now support targetGroupName - #2655 refresh

### PR DESCRIPTION
**Pull request by fatmcgav**
### Issue

Partially solves https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2373
#3586 
#3819 

### Description

This PR contains the changes from #2655 rebased against the latest `main` and updated to support `aws-sdk-go-v2`.

All credit goes to @marcosdiez for the original PR and changes.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by fatmcgav** [comment]
cc @johngmyers As you reviewed the previous PR 👍

**Comment by fatmcgav** [comment]
Hey @shraddhabang

Thanks for running the tests. I'm glad they all passed :)
Hopefully someone can review this soon and assuming all good then get it merged and released 🤞

**Comment by fatmcgav** [comment]
Thanks for the lgtm @wweiwei-li ... What's next to get this merged and released?

**Comment by fatmcgav** [comment]
I note that https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3853/ has recently been merged and released. 

I suspect this feature will further enhance and simplify the multi-cluster capabilities :)

**Comment by fatmcgav** [comment]
@shraddhabang / @wweiwei-li Nudge on this one ❤️

**Comment by MarcusDunn** [comment]
@shraddhabang / @wweiwei-li could you take a look at this / what it would take to get it merged? This change would be a huge QoL improvement for our deployments.

**Comment by fatmcgav** [comment]
@shraddhabang / @wweiwei-li I've rebased this branch from `master`, so please can we get this re-approved, merged and released :) ❤️

**Review by shraddhabang — APPROVED** [review]

**Review by zac-nixon — APPROVED** [review]

**Comment by fatmcgav** [comment]
🥳 Thanks @shraddhabang

**Comment by fatmcgav** [comment]
@shraddhabang Are you able to confirm when the next release is scheduled for? 👍

**Pull request merged**
