### PR TITLE
Issue #1609. Checking for taint ToBeDeletedByClusterAutoscaler while …

### PR DESCRIPTION
**Pull request by atulaggarwal**
…checking if node is suitable to handle traffic.

### CODE REVIEW

**Comment by atulaggarwal** [comment]
I am not sure if the base branch should be master or main. I wanted to get this into 1.x branch so that we can use it in our cluster. Currently we don't have immediate plan to move to 2.x

**Comment by atulaggarwal** [comment]
Can someone review the PR?

**Comment by kishorj** [comment]
@atulaggarwal Thanks for the PR, could you port the changes to main branch instead? The master branch is for the legacy v1 release, and we plan to limit the fixes to security related or critical issues only.

**Comment by atulaggarwal** [comment]
@kishorj - Thanks you. I have raised PR : #1688 on main branch. Closing this one.

**Pull request closed without merging**
