### PR TITLE
chore: Update go version to mitigate CVE

### PR DESCRIPTION
**Pull request by rajeeshckr**
### Description

This is to fix latest golang CVE https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M

-->

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by rajeeshckr** [comment]
@M00nF1sh could you please approve this if looks good

**Comment by yizhang-zen** [comment]
Kindly ping @oliviassss, wonder the time scheduled for next release.

**Pull request merged**
