### PR TITLE
Add metrics for managed load balancer resources

### PR DESCRIPTION
**Pull request by drewgonzales360**
### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller

### Description

I'm adding metrics so that users can view which Kubernetes services and ingresses are annotated for the aws-load-balancer controller. When services and ingresses are annotated properly, the corresponding load balancer is created an a gauge counts how many of these exist.

The prometheus gauge is tagged with:
- the name of the load balancer
- the type of load balancer (network or application)
- the namespace of the Kubernetes service/ingress
- the name of the Kubernetes service/ingress

Screenshot 2023-01-12 at 9 39 59 PM

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by johngmyers** [comment]
I don't quite see how this is worth the metrics cardinality it uses. It seems likely the report could be generated simply by querying the Kubernetes API for resources of the appropriate types and examining their statuses.

**Comment by drewgonzales360** [comment]
@johngmyers for one cluster, yeah I agree that asking the API server is fine. But when you run hundreds of clusters, it's easier to look at a dashboard.

**Comment by ItaloChagas** [comment]
I'm watching for news on this one. :)

**Comment by drewgonzales360** [comment]
Hey y'all! I was going through my backlog and found this sitting around. Gonna try and get a review 😄

**Comment by drewgonzales360** [comment]
I'm gonna close this for now since I don't need it anymore. If anyone wants to pick this up, feel free to create a new branch from this.

**Pull request closed without merging**
