### PR TITLE
Add default tags to backend SG

### PR DESCRIPTION
**Pull request by kishorj**
### Issue
Fixes: #2424

### Description
Add `default-tags` to the backend security group.

### Tests
Verified backend SG contained additional tags specified in default-tags configuration.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by johngmyers** [comment]
Shouldn't this use `MergeStringMap()` to reconcile overlapping tags, then pass to `convertTagsToSDKTags()`?

**Comment by johngmyers** [comment]
Alternatively, add `elbv2.k8s.aws/resource` to `config.trackingTagKeys`

**Review by orsenthil — APPROVED** [review]
LGTM.

**Pull request merged**
