### PR TITLE
add oliviassss as reviewer

### PR DESCRIPTION
**Pull request by oliviassss**
### Description

add oliviassss as reviewer and approver
### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Comment by johngmyers** [comment]
A requirement for approver is to have been a reviewer for at least three months.
/hold

**Comment by johngmyers** [comment]
Requirements for reviewer and approver are at https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by oliviassss** [comment]
@johngmyers changed to reviewer only.

**Comment by johngmyers** [comment]
@oliviassss Thank you. Could you enumerate the 5 PRs where you've been the primary reviewer and the 20 substantial PRs you've either reviewed or merged?

**Pull request merged**
