### PR TITLE
Adds parameter to create IngressClass Resource

### PR DESCRIPTION
**Pull request by lazouz**
### Issue

import PR by @emanuelflp from https://github.com/aws/eks-charts/pull/572

### Description

To use the ingressClass parameter inside of Ingress resource, the IngressClass needs to be already exists in cluster.

This changes adds a new parameter to create ingressClass Resource.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by kishorj** [comment]
Please update the chart version as well.

**Comment by lazouz** [comment]
Hi @kishorj @M00nF1sh the PR is ready for a review :)

**Pull request merged**
