### PR TITLE
Add new featuregate to enable/disable SG management

### PR DESCRIPTION
**Pull request by alikhanich**
### Issue
We have a lot of services in k8s with type LoadBalancer, and for each of them controller was creating SG in AWS. We've reached the point when quota increase was denied from AWS support. So we decided to disable SG management for controller and switch to static rule which allows 30000-32767 port range to 0.0.0.0/0.  Currently it can only be achieved by placing annotation on EACH service in k8s cluster, as our cluster is very big and there are a lot of different charts it is very hard for us. Hence here comes this PR.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2358

### Description

I have added new feature flag `ManageSecurityGroups` which is true by default for backwards compatibility, and in method `buildManageSecurityGroupRulesFlag` I preserved the ability to use annotations to disable SG management.
If you like this feature I will gladly write tests for it and will update the docs accordingly.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by djirik** [comment]
@kishorj @M00nF1sh Hi, any thoughts on this?

**Comment by johngmyers** [comment]
I'm planning on adding a `securityGroups` field to `IngressClassParams`. Would this solve your problem?

**Comment by djirik** [comment]
@johngmyers how would it work? and do you have ETA?

**Comment by johngmyers** [comment]
It would look like #2945 except for security groups instead of subnets.

I'm completely dependent on code reviews and approvals, so don't have an ETA. Security groups would be fourth on my list because I don't have a need to specify them myself. You could use my PR as a template.

**Comment by ngnix** [comment]
Hi @johngmyers !
I think it will be the best solution to add a `securityGroups` to the `IngressClassParams`.

**Comment by ngnix** [comment]
Maybe it's worth adding the ability to create a security group for each service with the LoadBalancer type? and add them only to those worker nodes on which the corresponding loads are located? The problem is that now it is very easy to run into two AWS limits:
 - number of rules within one security group 
 - number of security groupы per EC2 instance

This is a hard problem in AWS - as these limits are very small !

**Comment by ngnix** [comment]
The current solution proposed by @djirik  will allow turning off the creation of rules by the operator, in this case, ports of 30000+ services are always allowed in the security group and new rules are not added to it, so we do not rest on the limits.
This is an alternative solution.

**Pull request closed without merging**
