### PR TITLE
docs: Update v1 to v2 migration guide to include example command for updating SG rules

### PR DESCRIPTION
**Pull request by chancez**
Adds a command to the v1 to v2 upgrade guide documentation for updating the SG rules created by alb ingress controller v1 to include the elbv2.k8s.aws/targetGroupBinding=shared description.

I'm not 100% sure the formatting is correct on the markdown, but it should be easy to update if not.

### CODE REVIEW

**Comment by chancez** [comment]
Test failure is unrelated to my changes.

**Comment by kishorj** [comment]
> Test failure is unrelated to my changes.

@chancez, Thanks for the PR, the test failures are not due to your changes. I will get your changes for 2.2.0 release.

**Pull request merged**
