### PR TITLE
Upgrade Kubernetes libs to v0.29.x.

### PR DESCRIPTION
**Pull request by jlrgraham**
### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3649

### Description

Bumped the versions of all the `k8s.io` libraries to their latest `v0.29.x` versions:

```
grep k8s.io go.mod | grep -v indirect | awk '/0.26/ {print $1}' | xargs -I{} go get {}@v0.29
```

### Checklist
- [-] Added tests that cover your change (if possible)
- [-] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested (passed `make unit-test`)
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by connerstobie** [comment]
Bump, please review!

**Comment by aaroniscode** [comment]
@jlrgraham there are some inconsistencies with your go modules ... I checked out your branch and couldn't build the project.

Consider running `go mod tidy`.  Though I ran that and still couldn't build the project as there were some missing methods. I recommend using a clean build machine and checking out your PR so you can verify the issues and fix.

**Comment by aaroniscode** [comment]
@jlrgraham found what I think is at least part of the issue. [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) needs to be upgraded to at least [v0.15.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0).

https://github.com/kubernetes-sigs/controller-runtime/pull/2223 adds support to controller-runtime for with client-go 1.27 and higher. 

Note there are significant breaking changes when upgrading controller-runtime to v0.15.0 so this is looking a lot more complicated as I still can't get the project to build and I believe I'm hitting these breaking changes.

**Comment by oliviassss** [comment]
@jlrgraham, hey thanks for the contribution.
will you update the PR to address the comments?

**Pull request closed without merging**
