### PR TITLE
cut v2.7.0 release

### PR DESCRIPTION
**Pull request by shraddhabang**
### Issue

Releasing version 2.7.0

### Description

Releasing version 2.7.0

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Comment by alex-souslik-hs** [comment]
pretty sure the chart version is wrong

**Comment by oliviassss** [comment]
@alex-souslik-hs, hi the chart version has been fixed to v1.7.0, since it's a minor release.
Thanks for pointing out.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3551

**Pull request merged**
