### PR TITLE
alpn-policy: Don't require TLS target groups

### PR DESCRIPTION
**Pull request by iAnomaly**
### Issue

#2145 

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by iAnomaly** [comment]
I signed it

**Review by kishorj — APPROVED** [review]

**Comment by bixu** [comment]
@kishorj, any idea when `v2.3.0` will release? @iAnomaly's work will, we think, unblock my org's efforts to proxy OpenTelemetry gRPC traces through our NLBs.

CC: @ limoges / @svrakitin

**Pull request merged**
