### PR TITLE
Docs: Fix typo in `nlb.md`.

### PR DESCRIPTION
**Pull request by Gacko**
### Issue

No issue available.

### Description

This PR fixed a typo I stumbled over when reading the docs about NLBs.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by Gacko** [comment]
@johngmyers @kishorj Am I missing anything or does it just need time to proceed on this? :)

**Comment by Gacko** [comment]
Hm, I don't think the `pull-aws-load-balancer-controller-unit-test` failing is related to my change - is it?

**Comment by johngmyers** [comment]
It's an infrastructure problem, not related to the change.

**Comment by Gacko** [comment]
Hey @johngmyers! Just wanted to ask about the current state of this PR. Is there anything I can do to get it merged soon?

**Pull request merged**
