### PR TITLE
Enable Prometheus metrics without service monitor

### PR DESCRIPTION
**Pull request by prashcr**
### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3244

### Description

Add a `metrics.enabled` variable in the Helm chart to create the Prometheus metrics service independently of the service monitor. This enables monitoring for Kubernetes clusters that are using alternative Prometheus collectors and don't have Prometheus Operator/ServiceMonitor CRD installed.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested with `helm lint`, `helm template`
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
@prashcr, sorry for being late. can you please rebase the PR? I don't think it necessary to bump up the version in Chart.yaml, we will change the version when we are releasing.

Otherwise, the change looks good to me.

**Comment by prashcr** [comment]
@oliviassss No worries, updated.

**Comment by prashcr** [comment]
Could I get an approval?

**Pull request closed without merging**
