### PR TITLE
Controller does not delete listeners having specific tag (e.g. indicating listeners are externally managed)

### PR DESCRIPTION
**Pull request by paulzhang97**
### Issue

The controller removes listeners not recognized by itself. In some deployments, listeners are created outside of the controller and managed externally. We need a way to tell the controller not to delete such listeners during reconciliation.

Related [issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2638)

### Description

Listener synthesizer get the env variable `PREVENT_DELETION_TAG_NAME` specifying the tag name for not deleting listeners. It does not delete listeners tagged with the one set by `PREVENT_DELETION_TAG_NAME`.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by paulzhang97** [comment]
@kishorj @johngmyers This is my first PR. Just want to check whether you would need any action from me.

**Comment by paulzhang97** [comment]
Can we have some review on this PR?

**Comment by modevops** [comment]
I have the same issue as the user above.  ALB removes listeners not recognized by itself.   This makes it impossible to share aws alb controller with a non k8's service or ec2 instance.  I am doing path based routing and I have resource that uses to much memory and cpu and I do not want to migrate it to k8s.  I am stuck between a  rock and hard place because resources is used in so many parts they cannot change it.  Can this be escalated!!!! Please!!!!!

**Comment by paulzhang97** [comment]
@modevops I implemented it at the forked [repo](https://github.com/redpanda-data/aws-load-balancer-controller). Check it out to see whether it meets your needs.

**Pull request closed without merging**
