### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by stensonb**
Replacement for #2410

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by kishorj — APPROVED** [review]

**Comment by stensonb** [comment]
Yikes.  How do my changes break these tests?

**Comment by kishorj** [comment]
> Yikes. How do my changes break these tests?

doesn't look like your change. I will investigate further.

**Pull request merged**
