### PR TITLE
Update repo name to load-balancer

### PR DESCRIPTION
**Pull request by tyron**
### Description

Update repo name and URL due to rename from v1 to v2.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by tyron** [comment]
I signed it

**Comment by kishorj** [comment]
@tyron, thanks for your contribution. Did you run `make docs-preview` on your local repo after the changes, and verify that the mkdocs rendering works as expected?

**Comment by tyron** [comment]
@kishorj yes, I ran `make docs-preview` and I was able to navigate the docs in my local 127.0.0.1:8000 installation. Docs rendered as expected and navigation to GitHub repo works as well.

**Pull request merged**
