### PR TITLE
Add example for NLB target-group-attributes to enable unhealthy target connection draining

### PR DESCRIPTION
**Pull request by jukie**
### Description

Adds example for an additional target group attribute that's already supported

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by shraddhabang — APPROVED** [review]
/lgtm

**Comment by oliviassss** [comment]
The unit test and e2e test failing should not be related to this PR, but it's not allowing me to force merge the PR.

**Comment by jukie** [comment]
@oliviassss wouldn't that be due to the failed tests? It looks like the e2e test just timed out and a retest may help and the unit test also may have been a one-off?

**Comment by oliviassss** [comment]
@jukie, yeah usually for doc change these tests may not be necessary, but let's see if retest could pass.
/retest

**Pull request merged**
