### PR TITLE
maintain helm chart test.yaml file

### PR DESCRIPTION
**Pull request by BobDu**
Signed-off-by: BobDu <i@bobdu.cc>

### Description

`test.yaml` in helm chart release package is a incomprehensible and unused file.
Add `test.yaml` in `.helmignore`.
And best effort to keep it in sync with `values.yaml`.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by BobDu** [comment]
@fawadkhaliq  Can you have some time to see it?

**Comment by fawadkhaliq** [comment]
> @fawadkhaliq Can you have some time to see it?

@BobDu - I'm no longer a maintainer of this project. @M00nF1sh, @kishorj should be able to help.

**Review by kishorj — APPROVED** [review]

**Pull request merged**
