### PR TITLE
docs update for using annotations

### PR DESCRIPTION
**Pull request by jaydeokar**
### Issue
N/A

### Description
Added doc update about the use of annotations and expected behavior of the controller

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by johngmyers** [comment]
I cannot figure out what this update is trying to say.

**Comment by oliviassss** [comment]
@johngmyers, we got some internal tickets regarding the behavior that the controller reverts some manual edit on ingress/services/other resources during reconciliation, which is an expected behavior because the controller reconciles based on the manifest. So just to call it out in our doc to use annotation as best practice.

**Comment by johngmyers** [comment]
For one, annotations are not the best practice. For annotations which have a corresponding field in `IngressClassParams`, the field is best practice. For the `group.name` annotation, `IngressClass` is best practice. For the `target-type` annotation, the `--default-target-type` flag is best practice.

The sentence as written is not very comprehendable. What you're trying to say is that the controller manages the configuration of the LBs that it creates and if one wants to change the configuration of the LB one needs to do that through the configuration given to LBC.

**Comment by oliviassss** [comment]
@johngmyers, thanks for the feedback, maybe we add a high-level note in `aws-load-balancer-controller/docs/deploy/configurations.md` - 
The controller manages the configurations of the resources it creates, we do not recommend out-of-band modifications to these resources because the controller may revert the manual changes during reconciliation. We recommend to use configuration options provided as best practice, such as ingress and service annotations, controller command line flags and IngressClassParams.

**Comment by johngmyers** [comment]
That is much better wording, thanks. Consider `how-it-works.md` as the location; `configurations.md` is more about the command-line flags.

**Pull request closed without merging**
