### PR TITLE
cut v2.6.2 release

### PR DESCRIPTION
**Pull request by shraddhabang**
### Issue

Releasing v2.6.2 patch

### Description

cut v2.6.2 release

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by adit-cmd** [comment]
Hi @M00nF1sh / @shraddhabang  When pulling the 1.6.0 version, the image which is getting downloaded is public.ecr.aws/eks/aws-load-balancer-controller:**v2.6.0** instead of v2.6.2

**Comment by oliviassss** [comment]
@adit-cmd, the chart version for the v2.6.2 image should be 1.6.2, sorry for the confusion
see: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3457

**Comment by adit-cmd** [comment]
> @adit-cmd, the chart version for the v2.6.2 image should be 1.6.2, sorry for the confusion see: #3457

@oliviassss There still seems to be some confusion at my end. I assume the chart version 1.6.2 isn't released yet. If my assumption is incorrect can you please point me to the release where the chart version is 1.6.2?

I am trying to deploy the latest aws controller and as per [ https://github.com/kubernetes-sigs/aws-load-balancer-controller/ ] and I see the latest is v2.6.2. The chart version is 1.6.0. If we look the values yaml the image tag is 2.6.2. However its downloading v2.6.0. Isn't it supposed to download the image as per the tag?

**Comment by oliviassss** [comment]
@adit-cmd, for helm chart release please refer to `eks-chart`:https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

**Comment by adit-cmd** [comment]
> @adit-cmd, for helm chart release please refer to `eks-chart`:https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

Thanks @oliviassss . Can you kindly help me by clarifying the other issue I pointed out, regarding the values yaml.

**Pull request merged**
