### PR TITLE
Enable having multiple matching certs in autodiscover mode

### PR DESCRIPTION
**Pull request by LechG**
### Issue
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1598

### Description

When you don't provide the annotation for certificate arn, the controller tries to find a matching certificate in ACM by itself. However when multiple matching certs are found - it fails with 
"multiple certificate found for host: host, certARNs: [arn1, arn2]"

Which I believe is wronge because:
1. YOU CAN add multiple certificates via annotation
2. AWS has it's own algorithm of determining the best certificate to be used for the requests

To adjust this behavior, I removed the if clause that threw an error during setup of ALB in case there was more than one domain matching certificate in ACM.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [X] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by allupaku** [comment]
Hello team, any specific version , this will get merged into ? We are also looking forward for this

**Comment by blakepettersson** [comment]
@kishorj @M00nF1sh apart from the conflict with master and the CLA, what would be the showstopper to get this in?

**Comment by kishorj** [comment]
@LechG, thanks for your contribution. We will relax the single cert per host restriction in the v2.5.0 release, PR #3028 will address this. Closing this PR in favor of 3028.

**Pull request closed without merging**
