### PR TITLE
Documentation update to add missing annotation

### PR DESCRIPTION
**Pull request by blastik**
### Issue

[This](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/374) feature is missing in the docs

### Description

Just adding the documentation for it

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by kishorj** [comment]
@blastik, The controller doesn't support ignore-host-header in either v1 or v2 releases since it violates ingress spec for multi host ingresses. Please refer to issue  #776 for further details and the potential workarounds.

I'm closing this PR.

**Comment by blastik** [comment]
@kishorj are you sure? because I'm actively using it in the latest version of the controller

**Comment by kishorj** [comment]
@blastik, what is your current controller version?

**Comment by blastik** [comment]
> @blastik, what is your current controller version?

`v2.4.3`

**Pull request closed without merging**
