### PR TITLE
support for annotation aws-load-balancer-ip-target-label

### PR DESCRIPTION
**Pull request by santosh-kodali**
#1963 

This PR will allow for specification of Target IP from pod label with label specified from `service.beta.kubernetes.io/aws-load-balancer-ip-target-label`

Please advise on any modifications or additions.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
@santosh-kodali 
Thanks for making this contribution.
Would you explain the background for this PR? why the pod labels is needed. since ideally all these pods behind service should be registered

**Comment by santosh-kodali** [comment]
The reason behind this PR is that default service registration is based on podIP, however, we might want certain LBs to point towards a different IP attached to the node. I suppose we could have a custom endpoint reconciler to update the endpoints according to custom needs. I will close this PR if this functionality is not wanted.

**Comment by M00nF1sh** [comment]
@santosh-kodali 
Yes,  i think we don't want to introduce such feature(to further select pods behind service). 

For such use case, it's better to do what you suggested(have a separate controller to generate endpoints)

**Comment by santosh-kodali** [comment]
feature not required

**Pull request closed without merging**
