### PR TITLE
Added helm envFrom value parameter for cluster-name

### PR DESCRIPTION
**Pull request by omerap12**
### Issue

FIxes: #2729 
### Description
Add option to set the cluster name using envFrom.
for example, in values.yaml file:

```shell
envFrom:
    valueFrom:
      - secretRef:
           name: aws-load-balancer-controller

clusterName: ${clusterName}
```
and then the deployment will get the cluterName using the env variable (which got from the secret).

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
/lgtm
can you please add an entry for the `envFrom` in values.yaml, with some comments for the example input. Thanks.

**Comment by omerap12** [comment]
> /lgtm can you please add an entry for the `envFrom` in values.yaml, with some comments for the example input. Thanks.

sure. done :)

**Pull request merged**
