### PR TITLE
Cherry-picked commits for patch release v2.6.2

### PR DESCRIPTION
**Pull request by shraddhabang**
### Issue

Cherry-picked the commits for patch release of v2.6.2 from main

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
@shraddhabang, please cherry-pick this commit too: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3392

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
