### PR TITLE
update file paths in prow script for adc regions

### PR DESCRIPTION
**Pull request by oliviassss**
### Description

update the file paths for adc regions
### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Comment by oliviassss** [comment]
Need to have this PR megred to fix the ci e2e test job: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3392

**Pull request merged**
