### PR TITLE
fix typo in annotations doc

### PR DESCRIPTION
**Pull request by kishorj**
### Issue
Fix typo in the annotations doc.

### Description
The docs mentioned `deletion_protection.enable=true` instead of `deletion_protection.enabled=true`.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by kishorj** [comment]
Thanks to  @ShauliSolomovich for raising PR #2475

**Review by M00nF1sh — COMMENTED** [review]
/lgtm

**Pull request merged**
