### PR TITLE
fix: Add revisionHistoryLimit override

### PR DESCRIPTION
**Pull request by bodgit**
### Issue

n/a

### Description

This PR adds a chart override for setting `revisionHistoryLimit` on the Deployment. Default value is 10 which is the implicit Kubernetes default.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
@bodgit, can you please rebase the main branch to pick up the fix to e2e tests failure? I cannot merge it without test passing
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3539
thanks

**Comment by bodgit** [comment]
@oliviassss Done, that seems to have worked. I rebased yesterday to see if that would fix things but clearly I did it before the fix went in.

**Pull request merged**
