### PR TITLE
Add custom AWS endpoints configuration

### PR DESCRIPTION
**Pull request by papigers**
### Issue

#2176

### Description

Added command-line flags to configure each AWS endpoint used, which in turn is used to configure the AWS client.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by papigers** [comment]
I've signed the CLA

**Comment by papigers** [comment]
@kishorj @M00nF1sh any thoughts?

**Comment by papigers** [comment]
@kishorj sorry to nag, but I think the changes are pretty straightforward, can you review?

If you prefer that the configuration will be applied using environment variables, I would be happy to change the code.

**Comment by kishorj** [comment]
> @kishorj sorry to nag, but I think the changes are pretty straightforward, can you review?
> 
> If you prefer that the configuration will be applied using environment variables, I would be happy to change the code.

@papigers, thanks for your contribution. I agree, changes are straightforward. We've been pondering whether we should instead provide a single flag `aws-api-endpoints` and accept serialized input similar to the current flag `aws-api-throttle`. That will free us from having to maintain the AWS service list in the controller codebase. Let me know if you are interested to work on a single command line flag.

**Comment by papigers** [comment]
@kishorj good point, I'm on it!

**Comment by papigers** [comment]
@kishorj Just pushed what we discussed. Note that I've made the configuration struct implement the `endpoints.Resolver` interface so it can be passed directly to `WithEndpointResolver`. I'm not sure if that's the best approach but I figured it's redundant to create another struct/function just to do that.

**Comment by papigers** [comment]
@kishorj any update?

**Comment by kishorj** [comment]
> @kishorj any update?

I'll merge your changes this week. If I have further concerns, I will let you know.

**Review by kishorj — APPROVED** [review]

**Pull request merged**
