### PR TITLE
fix: typo in PR template

### PR DESCRIPTION
**Pull request by nakamume**
```diff
- Help your reviewers my guiding
+ Help your reviewers by guiding

```

### CODE REVIEW

**Review by johngmyers — APPROVED** [review]
/ok-to-test

**Comment by nakamume** [comment]
@johngmyers I can't figure out the reason for test failure. Though, I don't think this PR should have affected any tests.

**Comment by johngmyers** [comment]
It appears to be a problem with a missing credential.

**Comment by nakamume** [comment]
What can I do about it?

**Comment by johngmyers** [comment]
Nothing. This needs to be fixed by a test-infra maintainer.

**Review by kishorj — APPROVED** [review]

**Pull request merged**
