### PR TITLE
upgrade golang to v1.9.3

### PR DESCRIPTION
**Pull request by M00nF1sh**
### Description
Upgrade golang to v1.9.3

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by kishorj — APPROVED** [review]

**Comment by M00nF1sh** [comment]
/test pull-aws-load-balancer-controller-e2e-test
--


<br class="Apple-interchange-newline">

**Pull request merged**
