### PR TITLE
Release v2.7.2 - Cherry picked the commits from main

### PR DESCRIPTION
**Pull request by shraddhabang**
### Description

Release v2.7.2 - Cherry picked the commits from main

Ran and verified E2E tests on the test image with these commits. 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by ikosenn** [comment]
Hey @shraddhabang is it possible to include commit ac21af638efdbf378f194b88ed12b70b5b0ae50a

**Comment by shraddhabang** [comment]
> Hey @shraddhabang is it possible to include commit [ac21af6](https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/ac21af638efdbf378f194b88ed12b70b5b0ae50a)?

Hey @ikosenn , We are planning release of your commit for v2.8.0 as its a big change for a patch release and we need to get internal security sign off for this feature addition.

**Comment by ikosenn** [comment]
> > Hey @shraddhabang is it possible to include commit [ac21af6](https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/ac21af638efdbf378f194b88ed12b70b5b0ae50a)?
> 
> Hey @ikosenn , We are planning release of your commit for v2.8.0 as its a big change for a patch release and we need to get internal security sign off for this feature addition. The current ETA for next minor release is end of April.

Thanks for the quick response. Makes it sound serious. Might you have an ETA on when 2.8.0 might be out?

**Comment by shraddhabang** [comment]
> > > Hey @shraddhabang is it possible to include commit [ac21af6](https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/ac21af638efdbf378f194b88ed12b70b5b0ae50a)?
> > 
> > 
> > Hey @ikosenn , We are planning release of your commit for v2.8.0 as its a big change for a patch release and we need to get internal security sign off for this feature addition. The current ETA for next minor release is end of April.
> 
> Thanks for the quick response. Makes it sound serious. Might you have an ETA on when 2.8.0 might be out?

No worries. This is a standard process for such a large contribution. We are tracking it for end of April or early May.

**Comment by ikosenn** [comment]
> > > > Hey @shraddhabang is it possible to include commit [ac21af6](https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/ac21af638efdbf378f194b88ed12b70b5b0ae50a)?
> > > 
> > > 
> > > Hey @ikosenn , We are planning release of your commit for v2.8.0 as its a big change for a patch release and we need to get internal security sign off for this feature addition. The current ETA for next minor release is end of April.
> > 
> > 
> > Thanks for the quick response. Makes it sound serious. Might you have an ETA on when 2.8.0 might be out?
> 
> No worries. This is a standard process for such a large contribution. We are tracking it for end of April or early May.

Thanks. Will keep an eye on it.

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
