### PR TITLE
Add johngmyers as approver

### PR DESCRIPTION
**Pull request by johngmyers**
### Issue

N/A

### Description

Promotes johngmyers to approver

Requirements:

- [x] Reviewer of the codebase for at least 3 months
- [x] Primary reviewer for at least 10 substantial PRs to the codebase

#2950, #2942, #2425, #2963, #2988,
#2986, #3269, #3147, #2735, #3312,
#3332, #3343, #3347,

- [x] Reviewed or merged at least 30 PRs to the codebase

#2950, #2942, #2880, #2866, #2453,
#2435, #2433, #2425, #2442, #2500,
#2443, #2963, #2735, #2881, #2840,
#2987, #2988, #2992, #2993, #2955,
#2990, #2945, #3007, #3025, #3269,
#3147,  #3292, #3272, #3318, #3332,
#3343, #3347,

- [ ] Nominated by a subproject owner
   - [ ] With no objections from other subproject owners
   - [x] Done through PR to update the top-level OWNERS file

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by oliviassss** [comment]
@johngmyers, thanks for the contribution!
/lgtm

**Comment by oliviassss** [comment]
@johngmyers, sorry for the late update. We need to check with our leadership because we have internal process to merge and release PRs selectively.

**Comment by johngmyers** [comment]
This would be a good topic for the Provider-AWS meeting on Friday. I would also be amenable to an unofficial meeting.

**Review by M00nF1sh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
